CREATE TABLE GHARKAHISAB_EXPENSES
(
  EXPENSE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  EXPENSE_TYPE_ID 	SMALLINT,
  EXPENSE_DATE DATE,
  DESCRIPTION 	VARCHAR(200),
  AMOUNT DECIMAL(20,2),
  USER_ID VARCHAR(20),
  ACCOUNTING_YEAR_MONTH MEDIUMINT 
);

CREATE TABLE GHARKAHISAB_ACC_YEAR_MONTHS
(
  ACCOUNTING_YEAR_MONTH MEDIUMINT ,
  CLOSED_DATE DATE
);

INSERT INTO GHARKAHISAB_ACC_YEAR_MONTHS(ACCOUNTING_YEAR_MONTH)VALUES(201403);
INSERT INTO GHARKAHISAB_ACC_YEAR_MONTHS(ACCOUNTING_YEAR_MONTH)VALUES(201402);
INSERT INTO GHARKAHISAB_ACC_YEAR_MONTHS(ACCOUNTING_YEAR_MONTH)VALUES(201401);


CREATE TABLE GHARKAHISAB_PAYMENTS
(
  PAYMENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  PAYMENT_FROM 	INT,
  PAYMENT_DATE DATE,
  DESCRIPTION 	VARCHAR(200),
  AMOUNT DECIMAL(20,2),
  USER_ID VARCHAR(20),
  ACCOUNTING_YEAR_MONTH MEDIUMINT 
);


CREATE TABLE GHARKAHISAB_USERS
(
  USER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  NAME 	VARCHAR(25),
  CASH_PAY VARCHAR(1)
);

INSERT INTO GHARKAHISAB_USERS(NAME)VALUES('Latish');
INSERT INTO GHARKAHISAB_USERS(NAME)VALUES('Kishore');
INSERT INTO GHARKAHISAB_USERS(NAME)VALUES('Amma');
INSERT INTO GHARKAHISAB_USERS(NAME)VALUES('Dad');
INSERT INTO GHARKAHISAB_USERS(NAME)VALUES('Seema');

UPDATE GHARKAHISAB_USERS SET CASH_PAY='Y' WHERE NAME IN ('Latish','Kishore');

CREATE TABLE GHARKAHISAB_EXPENSE_TYPES
(
  EXPENSE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  DESCRIPTION 	VARCHAR(25),
  SORT_ORDER SMALLINT
);
INSERT INTO GHARKAHISAB_EXPENSE_TYPES(DESCRIPTION,SORT_ORDER)VALUES('Food items / Grocery',1);
INSERT INTO GHARKAHISAB_EXPENSE_TYPES(DESCRIPTION,SORT_ORDER)VALUES('50-50',2);
INSERT INTO GHARKAHISAB_EXPENSE_TYPES(DESCRIPTION,SORT_ORDER)VALUES('Personal expense - Latish',3);
INSERT INTO GHARKAHISAB_EXPENSE_TYPES(DESCRIPTION,SORT_ORDER)VALUES('Personal expense - Kishore',4);


CREATE TABLE GHARKAHISAB_EXPENSE_RULES
( EXPENSE_TYPE_ID  INT, 
  CHARGE_TYPE 	VARCHAR(25),
  USER_ID SMALLINT	
);

INSERT INTO GHARKAHISAB_EXPENSE_RULES(EXPENSE_TYPE_ID,CHARGE_TYPE)VALUES(1,'CHARGE_AS_RATIO');
INSERT INTO GHARKAHISAB_EXPENSE_RULES(EXPENSE_TYPE_ID,CHARGE_TYPE)VALUES(2,'CHARGE_EQUAL');
INSERT INTO GHARKAHISAB_EXPENSE_RULES(EXPENSE_TYPE_ID,CHARGE_TYPE,USER_ID)VALUES(3,'CHARGE_FULL',(select user_id from GHARKAHISAB_USERS where name='Latish'));
INSERT INTO GHARKAHISAB_EXPENSE_RULES(EXPENSE_TYPE_ID,CHARGE_TYPE,USER_ID)VALUES(4,'CHARGE_FULL',(select user_id from GHARKAHISAB_USERS where name='Kishore'));


CREATE TABLE GHARKAHISAB_USERS_EXPENSE_RATIO
(
  ACC_YEAR_MONTH INT,
  USER_ID INT , 
  TOTAL_COUNT SMALLINT,
  ALLOCATED_COUNT SMALLINT  
);

INSERT INTO GHARKAHISAB_USERS_EXPENSE_RATIO(ACC_YEAR_MONTH,USER_ID,TOTAL_COUNT,ALLOCATED_COUNT)VALUES(201403,(select user_id from GHARKAHISAB_USERS where name='Latish'),4,3);
INSERT INTO GHARKAHISAB_USERS_EXPENSE_RATIO(ACC_YEAR_MONTH,USER_ID,TOTAL_COUNT,ALLOCATED_COUNT)VALUES(201403,(select user_id from GHARKAHISAB_USERS where name='Kishore'),4,1);

